"""create_cheating_risk_analysis

Revision ID: 66c6810e9907
Revises: 
Create Date: 2026-06-11 13:02:10.254532
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '66c6810e9907'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cheating_risk_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('cheating_probability', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('activity_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('face_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suspicious_timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cheating_risk_analysis_exam_id'), 'cheating_risk_analysis', ['exam_id'], unique=False)
    op.create_index(op.f('ix_cheating_risk_analysis_participant_id'), 'cheating_risk_analysis', ['participant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cheating_risk_analysis_participant_id'), table_name='cheating_risk_analysis')
    op.drop_index(op.f('ix_cheating_risk_analysis_exam_id'), table_name='cheating_risk_analysis')
    op.drop_table('cheating_risk_analysis')
    # ### end Alembic commands ###
